# Generated by Django 3.0.2 on 2020-03-03 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=255)),
                ('Employer', models.CharField(max_length=255)),
                ('JobURL', models.URLField(blank=True, null=True)),
                ('JobLevel', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Availability', models.DateField()),
                ('Description', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'db_table': 'Job',
            },
        ),
    ]
