# Generated by Django 3.0.2 on 2020-03-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itBoardApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventTitle',
            new_name='title',
        ),
    ]
